image: gitpod/workspace-full

tasks:
  - init: npm install
    command: npm start

ports:
  - port: 1337
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true
